sudo: false
language: d
d:
    - dmd
    - dmd-nightly
    - ldc
    - ldc-beta

os:
    - linux
    
install:
    - wget -q "http://bit.ly/Doveralls" -O - | bash
    - chmod +x doveralls

script:
    - dub test --build=unittest-cov --compiler=${DC}
    - ./doveralls -travis-pro
