sudo: false
language: d
d:
    - dmd
    - dmd-nightly
    - ldc
    - ldc-beta

os:
    - linux

script:
    - dub test --build=unittest-cov --compiler=${DC}
    - dub fetch doveralls
    - dub run doveralls -- -travis-pro
